/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/carts/{cartGuid}/items/{cartItemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * delete-cart-item
     * @description delete-cart-item
     */
    delete: operations['delete-cart-item'];
    options?: never;
    head?: never;
    /**
     * patch-cart-item
     * @description patch-cart-item
     */
    patch: operations['patch-cart-item'];
    trace?: never;
  };
  '/search/suggestions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * get-search-suggestions
     * @description get-search-suggestions
     */
    get: operations['get-search-suggestions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/carts/{cartGuid}/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * get-cart-summary
     * @description get-cart-summary
     */
    get: operations['get-cart-summary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/carts/{cartGuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * get-cart
     * @description get-cart
     */
    get: operations['get-cart'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/carts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * post-carts
     * @description post-carts
     */
    post: operations['post-carts'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/carts/{cartGuid}/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * post-cart-items
     * @description post-cart-items
     */
    post: operations['post-cart-items'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/search/instant': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * get-search-instant
     * @description get-search-instant
     */
    get: operations['get-search-instant'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/content/message-bar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * get-message-bar
     * @description get-message-bar
     */
    get: operations['get-message-bar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddCartItemRequestModel: {
      /** Format: int32 */
      modelId: number;
      partNumberCode: string | null;
      /** Format: int32 */
      quantity: number;
      /** Format: int32 */
      supplementaryToCartItemId?: number;
    };
    /**
     * @description Ecommerce brand (division / site). Numeric values match legacy brand_id where applicable.
     * @enum {string}
     */
    Brand: 'giant' | 'liv' | 'momentum' | 'cadex';
    CalculatedTotalValueResponseModel: {
      currency: string;
      /** Format: double */
      discountTotal?: number;
      discountTotalFormatted?: string | null;
      orderHandlingFees?:
        | components['schemas']['OrderHandlingFeeResponseModel'][]
        | null;
      /** Format: double */
      orderHandlingTotal?: number;
      orderHandlingTotalFormatted?: string | null;
      /** Format: double */
      subTotal?: number;
      subTotalFormatted: string;
      /** Format: double */
      total?: number;
      totalFormatted: string;
    };
    CartItemRelationResponseModel: {
      /** Format: int32 */
      parentId?: number;
      quantityLimitationType?: components['schemas']['QuantityLimitationType'];
      type?: components['schemas']['CartItemRelationType'];
    };
    /** @enum {string} */
    CartItemRelationType: 'bundle' | 'supplementary';
    CartItemResponseModel: {
      attributes: {
        [key: string]: string;
      };
      categories: string[];
      hasNoStock: boolean;
      /** Format: int32 */
      id: number;
      imageBigUrl: string;
      imageUrl: string;
      isClearanceFinalSale: boolean;
      /** Format: int32 */
      maxQuantity?: number;
      name: string;
      partNumberCode: string;
      price: components['schemas']['MonetaryValueDiscountResponseModel'];
      /** Format: int32 */
      productId?: number;
      productType?: components['schemas']['ProductType'];
      /** Format: int32 */
      quantity: number;
      relation?:
        | unknown
        | components['schemas']['CartItemRelationResponseModel'];
      total: components['schemas']['CalculatedTotalValueResponseModel'];
      url: string;
    };
    CartResponseModel: {
      /** Format: uuid */
      guid?: string;
      /** Format: int32 */
      id?: number;
      items: components['schemas']['CartItemResponseModel'][];
      locked?: boolean;
      total: components['schemas']['CalculatedTotalValueResponseModel'];
    };
    CartSummaryResponseModel: {
      /** Format: uuid */
      guid?: string;
      /** Format: int32 */
      id?: number;
      locked?: boolean;
      /** Format: int32 */
      numberOfCartItems?: number;
    };
    CreateCartResponseModel: {
      /** Format: uuid */
      cartGuid: string;
    };
    /** @enum {string} */
    EcommerceBrand: 'giant' | 'liv' | 'momentum';
    /** @description Non-product content row in instant search. */
    InstantSearchContentHitModel: {
      contentType: components['schemas']['InstantSearchContentKind'];
      /** @description Same as with match spans marked for display (e.g. HTML <mark>); null when not provided by the backend. */
      highlightedName?: string | null;
      name: string;
      url: string;
    };
    /** @enum {string} */
    InstantSearchContentKind: 'discover' | 'articleOrPage' | 'news';
    /** @description Product row in instant search. */
    InstantSearchProductHitModel: {
      brand?: unknown | components['schemas']['EcommerceBrand'];
      categoryName: string;
      /** @description Same as with match spans marked for display (e.g. HTML <mark>); null when not provided by the backend. */
      highlightedCategoryName?: string | null;
      /** @description Same as with match spans marked for display (e.g. HTML <mark>); null when not provided by the backend. */
      highlightedName?: string | null;
      imageUrl: string;
      name: string;
      productType: components['schemas']['InstantSearchProductType'];
      url: string;
    };
    /** @enum {string} */
    InstantSearchProductType: 'bike' | 'gear';
    /** @description Instant search payload: up to five mixed bike/gear products and one content list (max two items per ). */
    InstantSearchResponseModel: {
      /** @description Full suggested phrase from the indexer when is set (e.g. "TCR Advanced"); null otherwise. */
      autocompleteFullPhrase?: string | null;
      /** @description Characters to append after the current query for inline autocomplete (e.g. query "TCR" and full phrase "TCR Advanced" yields " Advanced"); null when none. */
      autocompleteSuggestion?: string | null;
      /** @description Non-product hits (Discover, articles/pages, news), at most two per . */
      content: components['schemas']['InstantSearchContentHitModel'][];
      /** @description Product suggestions (bikes and gear), merged by relevance with a maximum of five items; one empty category yields more of the other. */
      products: components['schemas']['InstantSearchProductHitModel'][];
      /**
       * Format: int32
       * @description Total number of matching instant-search results before per-type and per-column caps are applied.
       */
      totalCount: number;
    };
    /** @description Message bar copy from interface_texts. */
    MessageBarResponseModel: {
      linkLabel?: string | null;
      linkUrl?: string | null;
      message?: string | null;
    };
    MonetaryValueDiscountResponseModel: {
      /** Format: double */
      amount?: number;
      amountFormatted?: string | null;
      currency: string;
      /** Format: double */
      originalAmount?: number;
      originalAmountFormatted?: string | null;
    };
    OrderHandlingFeeResponseModel: {
      /** Format: double */
      amount?: number;
      amountFormatted: string;
      description?: string | null;
      title?: string | null;
    };
    ProblemDetails: {
      detail?: string | null;
      instance?: string | null;
      /** Format: int32 */
      status?: number;
      title?: string | null;
      type?: string | null;
    };
    /** @enum {string} */
    ProductType: 'bike' | 'gear';
    /** @enum {string} */
    QuantityLimitationType: 'oneSkuPerProduct' | 'eachSkuOnce' | 'unlimited';
    /** @description A single suggested category or destination shown when search is opened without a query. */
    SearchSuggestionItemModel: {
      name: string;
      url: string;
    };
    SearchSuggestionsResponseModel: {
      suggestions: components['schemas']['SearchSuggestionItemModel'][];
    };
    UpdateCartItemQuantityRequestModel: {
      /** Format: int32 */
      quantity: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'delete-cart-item': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description - */
        cartGuid: string;
        /** @description - */
        cartItemId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'patch-cart-item': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description - */
        cartGuid: string;
        /** @description - */
        cartItemId: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        /**
         * @example {
         *       "quantity": 0
         *     }
         */
        'application/json': components['schemas']['UpdateCartItemQuantityRequestModel'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'get-search-suggestions': {
    parameters: {
      query: {
        /** @description - */
        Brand: string;
        /** @description Locale in culture-region format (e.g. en-US, nl-NL). Must be a valid .NET culture with region. */
        Locale: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "suggestions": [
           *         {
           *           "name": "string",
           *           "url": "string"
           *         }
           *       ]
           *     }
           */
          'application/json': components['schemas']['SearchSuggestionsResponseModel'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'get-cart-summary': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description - */
        cartGuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "guid": "string",
           *       "id": 0,
           *       "locked": true,
           *       "numberOfCartItems": 0
           *     }
           */
          'application/json': components['schemas']['CartSummaryResponseModel'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'get-cart': {
    parameters: {
      query: {
        /** @description Locale in culture-region format (e.g. en-US, nl-NL). Must be a valid .NET culture with region. */
        Locale: string;
      };
      header?: never;
      path: {
        /** @description - */
        cartGuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "guid": "string",
           *       "id": 0,
           *       "items": [
           *         {
           *           "attributes": {},
           *           "categories": [
           *             "string"
           *           ],
           *           "hasNoStock": true,
           *           "id": 0,
           *           "imageBigUrl": "string",
           *           "imageUrl": "string",
           *           "isClearanceFinalSale": true,
           *           "maxQuantity": 0,
           *           "name": "string",
           *           "partNumberCode": "string",
           *           "price": {
           *             "amount": 0,
           *             "amountFormatted": "string",
           *             "currency": "string",
           *             "originalAmount": 0,
           *             "originalAmountFormatted": "string"
           *           },
           *           "productId": 0,
           *           "productType": "bike",
           *           "quantity": 0,
           *           "relation": {},
           *           "total": {
           *             "currency": "string",
           *             "discountTotal": 0,
           *             "discountTotalFormatted": "string",
           *             "orderHandlingFees": [
           *               {
           *                 "amount": 0,
           *                 "amountFormatted": "string",
           *                 "description": "string",
           *                 "title": "string"
           *               }
           *             ],
           *             "orderHandlingTotal": 0,
           *             "orderHandlingTotalFormatted": "string",
           *             "subTotal": 0,
           *             "subTotalFormatted": "string",
           *             "total": 0,
           *             "totalFormatted": "string"
           *           },
           *           "url": "string"
           *         }
           *       ],
           *       "locked": true,
           *       "total": {
           *         "currency": "string",
           *         "discountTotal": 0,
           *         "discountTotalFormatted": "string",
           *         "orderHandlingFees": [
           *           {
           *             "amount": 0,
           *             "amountFormatted": "string",
           *             "description": "string",
           *             "title": "string"
           *           }
           *         ],
           *         "orderHandlingTotal": 0,
           *         "orderHandlingTotalFormatted": "string",
           *         "subTotal": 0,
           *         "subTotalFormatted": "string",
           *         "total": 0,
           *         "totalFormatted": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['CartResponseModel'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'post-carts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "cartGuid": "string"
           *     }
           */
          'application/json': components['schemas']['CreateCartResponseModel'];
        };
      };
    };
  };
  'post-cart-items': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description - */
        cartGuid: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        /**
         * @example {
         *       "modelId": 0,
         *       "partNumberCode": "string",
         *       "quantity": 0,
         *       "supplementaryToCartItemId": 0
         *     }
         */
        'application/json': components['schemas']['AddCartItemRequestModel'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "guid": "string",
           *       "id": 0,
           *       "items": [
           *         {
           *           "attributes": {},
           *           "categories": [
           *             "string"
           *           ],
           *           "hasNoStock": true,
           *           "id": 0,
           *           "imageBigUrl": "string",
           *           "imageUrl": "string",
           *           "isClearanceFinalSale": true,
           *           "maxQuantity": 0,
           *           "name": "string",
           *           "partNumberCode": "string",
           *           "price": {
           *             "amount": 0,
           *             "amountFormatted": "string",
           *             "currency": "string",
           *             "originalAmount": 0,
           *             "originalAmountFormatted": "string"
           *           },
           *           "productId": 0,
           *           "productType": "bike",
           *           "quantity": 0,
           *           "relation": {},
           *           "total": {
           *             "currency": "string",
           *             "discountTotal": 0,
           *             "discountTotalFormatted": "string",
           *             "orderHandlingFees": [
           *               {
           *                 "amount": 0,
           *                 "amountFormatted": "string",
           *                 "description": "string",
           *                 "title": "string"
           *               }
           *             ],
           *             "orderHandlingTotal": 0,
           *             "orderHandlingTotalFormatted": "string",
           *             "subTotal": 0,
           *             "subTotalFormatted": "string",
           *             "total": 0,
           *             "totalFormatted": "string"
           *           },
           *           "url": "string"
           *         }
           *       ],
           *       "locked": true,
           *       "total": {
           *         "currency": "string",
           *         "discountTotal": 0,
           *         "discountTotalFormatted": "string",
           *         "orderHandlingFees": [
           *           {
           *             "amount": 0,
           *             "amountFormatted": "string",
           *             "description": "string",
           *             "title": "string"
           *           }
           *         ],
           *         "orderHandlingTotal": 0,
           *         "orderHandlingTotalFormatted": "string",
           *         "subTotal": 0,
           *         "subTotalFormatted": "string",
           *         "total": 0,
           *         "totalFormatted": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['CartResponseModel'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'get-search-instant': {
    parameters: {
      query: {
        /** @description - */
        Brand: string;
        /** @description Locale in culture-region format (e.g. en-US, nl-NL). Must be a valid .NET culture with region. */
        Locale: string;
        /** @description - */
        Query: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "autocompleteFullPhrase": "string",
           *       "autocompleteSuggestion": "string",
           *       "content": [
           *         {
           *           "contentType": "discover",
           *           "highlightedName": "string",
           *           "name": "string",
           *           "url": "string"
           *         }
           *       ],
           *       "products": [
           *         {
           *           "brand": {},
           *           "categoryName": "string",
           *           "highlightedCategoryName": "string",
           *           "highlightedName": "string",
           *           "imageUrl": "string",
           *           "name": "string",
           *           "productType": "bike",
           *           "url": "string"
           *         }
           *       ],
           *       "totalCount": 0
           *     }
           */
          'application/json': components['schemas']['InstantSearchResponseModel'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  'get-message-bar': {
    parameters: {
      query: {
        /** @description - */
        Brand: string;
        /** @description Locale in culture-region format (e.g. en-US, nl-NL). Must be a valid .NET culture with region. */
        Locale: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "linkLabel": "string",
           *       "linkUrl": "string",
           *       "message": "string"
           *     }
           */
          'application/json': components['schemas']['MessageBarResponseModel'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": "string",
           *       "instance": "string",
           *       "status": 0,
           *       "title": "string",
           *       "type": "string"
           *     }
           */
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
}
